### ISSUE TITLE
how change color of the button

### ISSUE THREAD

**Issue by boardmain** [arn00s/cariocamenu#5]
how change color of the button?

**Comment by Tibb** [comment]
I suggest to change the image (_Ressources/Images/demoContent/icon-small.png_) with your own. It allows you to have a different color and a completely different icon if necessary ;)

Otherwise, you can tint the image (there are some simple stuff to do that on an _UIImageView_) but, since the actual image includes different colors and colors variations, I wouldn't recommend it.

Hope it helped

**Comment by boardmain** [comment]
@hi, that image isn't the background of the menu button (is the image in the content page)
if you run the demo the menu is blue.. and not yellow like that image
i want to change the background of the menu button

**Comment by boardmain** [comment]
ok found 

line 546 CariocaMenu.swift

```
let indicator = CariocaMenuIndicatorView(indicatorEdge: edge, size:CGSizeMake(47, 40), shapeColor:UIColor(red:0.07, green:1.0, blue:0.86, alpha:1))
```

**Comment by zigzagg16** [comment]
Thanks to @Tibb for the suggestion! 😃 in a next release I'll make it easier to change!
